# Generated by Django 5.0.1 on 2026-03-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_add_enrollment_request_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="default_protocol_sign_method",
            field=models.CharField(
                choices=[
                    ("both", "SMS и ЭЦП"),
                    ("sms", "Только SMS"),
                    ("eds", "Только ЭЦП"),
                ],
                default="both",
                max_length=10,
                verbose_name="Способ подписания протоколов по умолчанию",
            ),
        ),
    ]
