# Generated by Django 5.0.1 on 2026-03-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_add_default_protocol_sign_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="allow_eds_without_cert_iin",
            field=models.BooleanField(
                default=False, verbose_name="Разрешить ЭЦП без ИИН в сертификате"
            ),
        ),
    ]
