# Generated by Django 5.0.1 on 2026-03-05 20:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_add_allow_eds_without_cert_iin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="siteconfig",
            name="allow_eds_without_cert_iin",
        ),
    ]
