# Generated by Django 5.2.12 on 2026-04-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_siteconfig_sms_completion_flags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfig",
            name="default_protocol_sign_method",
            field=models.CharField(
                choices=[
                    ("both", "SMS и ЭЦП"),
                    ("sms", "Только SMS"),
                    ("eds", "Только ЭЦП"),
                    ("none", "Без SMS и ЭЦП"),
                ],
                default="both",
                max_length=10,
                verbose_name="Способ подписания протоколов по умолчанию",
            ),
        ),
    ]
