# Generated by Django 4.2.16 on 2026-01-22 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0009_add_is_standalone'),
        ('certificates', '0003_add_test_field_to_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='test',
            field=models.ForeignKey(blank=True, help_text='Test for standalone test completion certificates', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='tests.test'),
        ),
    ]
