# Generated by Django 4.2.29 on 2026-04-05 11:42

import apps.exams.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0004_add_termination_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="testattempt",
            name="screen_recording",
            field=models.FileField(
                blank=True,
                help_text="Screen recording of test attempt",
                null=True,
                upload_to=apps.exams.models.test_attempt_screen_upload_to,
            ),
        ),
    ]
