# Generated by Django 4.2.16 on 2026-01-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_smsverificationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsverificationcode',
            name='purpose',
            field=models.CharField(choices=[('protocol_sign', 'Protocol Signing'), ('registration', 'Registration'), ('password_reset', 'Password Reset'), ('verification', 'General Verification'), ('profile_update', 'Profile Update')], default='verification', max_length=20),
        ),
    ]
