# Generated by Django 5.2.12 on 2026-04-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_add_protocol_sign_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                help_text="Фото для идентификации при прохождении тестов с видеозаписью",
                null=True,
                upload_to="profiles/",
            ),
        ),
    ]
