# Generated by Django 5.2.12 on 2026-04-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="protocol_sign_method",
            field=models.CharField(
                choices=[
                    ("both", "SMS и ЭЦП"),
                    ("sms", "Только SMS"),
                    ("eds", "Только ЭЦП"),
                    ("none", "Без SMS и ЭЦП"),
                ],
                default="both",
                help_text="Способ подписания протоколов для членов ЭК",
                max_length=10,
            ),
        ),
    ]
