# Generated by Django 5.2.12 on 2026-04-11 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_protocol_sign_simple"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("name_kz", models.CharField(blank=True, max_length=200)),
                ("name_en", models.CharField(blank=True, max_length=200)),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="accounts.usercategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "User category",
                "verbose_name_plural": "User categories",
                "db_table": "user_categories",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="user_categories",
            field=models.ManyToManyField(
                blank=True,
                help_text="Категории пользователя (иерархия в UserCategory)",
                related_name="users",
                to="accounts.usercategory",
            ),
        ),
        migrations.AddConstraint(
            model_name="usercategory",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", False)),
                fields=("parent", "name"),
                name="uniq_user_category_parent_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="usercategory",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", True)),
                fields=("name",),
                name="uniq_user_category_root_name",
            ),
        ),
    ]
