# Generated by Django 4.2.16 on 2026-01-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_add_is_standalone_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='ppt_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('video', 'Video'), ('pdf', 'PDF'), ('ppt', 'PPT'), ('quiz', 'Quiz')], default='text', max_length=20),
        ),
    ]
