# Generated by Django 4.2.16 on 2026-01-29 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_add_course_enrollment_request'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='courseenrollmentrequest',
            new_name='course_enro_user_id_bafae6_idx',
            old_name='course_enro_user_id_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='courseenrollmentrequest',
            new_name='course_enro_status_bde1f5_idx',
            old_name='course_enro_status_abc123_idx',
        ),
    ]
