# Generated by Django 5.2.12 on 2026-04-11 15:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "courses",
            "0010_rename_course_enro_user_id_abc123_idx_course_enro_user_id_bafae6_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="ec_reviewers",
            field=models.ManyToManyField(
                blank=True,
                help_text="If empty, all EC members (pdek_member / pdek_chairman) review protocols for this category.",
                related_name="ec_review_categories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
