# Generated by Django 5.2.12 on 2026-04-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0011_category_ec_reviewers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("video", "Video"),
                    ("pdf", "PDF"),
                    ("combined", "Combined"),
                    ("ppt", "PPT"),
                    ("quiz", "Quiz"),
                ],
                default="text",
                max_length=20,
            ),
        ),
    ]
