# Generated by Django 4.2.27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('name_kz', models.CharField(blank=True, max_length=100, verbose_name='Название (каз)')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='Название (англ)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Категория новости',
                'verbose_name_plural': 'Категории новостей',
                'db_table': 'news_categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_kz', models.CharField(blank=True, max_length=255, verbose_name='Заголовок (казахский)')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='Заголовок (английский)')),
                ('excerpt', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('excerpt_kz', models.TextField(blank=True, verbose_name='Краткое описание (казахский)')),
                ('excerpt_en', models.TextField(blank=True, verbose_name='Краткое описание (английский)')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('content_kz', models.TextField(blank=True, verbose_name='Содержание (казахский)')),
                ('content_en', models.TextField(blank=True, verbose_name='Содержание (английский)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Изображение')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликована')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='news.newscategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'db_table': 'news',
                'ordering': ['order', '-published_at', '-created_at'],
            },
        ),
    ]
