# Generated by Django 4.2.16 on 2026-01-29 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0013_add_test_assignment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='testassignment',
            new_name='test_assign_user_id_abc384_idx',
            old_name='test_assign_user_test_status_idx',
        ),
        migrations.RenameIndex(
            model_name='testassignment',
            new_name='test_assign_status_0b09de_idx',
            old_name='test_assign_status_assigned_idx',
        ),
        migrations.RenameIndex(
            model_name='testenrollmentrequest',
            new_name='test_enroll_user_id_bae80a_idx',
            old_name='test_enroll_user_id_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='testenrollmentrequest',
            new_name='test_enroll_status_1aadb1_idx',
            old_name='test_enroll_status_abc123_idx',
        ),
    ]
