# Generated by Django 4.2.29 on 2026-04-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "tests",
            "0014_rename_test_assign_user_test_status_idx_test_assign_user_id_abc384_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="requires_screen_recording",
            field=models.BooleanField(
                default=False, help_text="Require screen capture recording during test"
            ),
        ),
    ]
