# Generated by Django 5.2.12 on 2026-04-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("protocols", "0005_add_eds_signature_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protocolsignature",
            name="sign_type",
            field=models.CharField(
                choices=[
                    ("otp", "OTP (SMS)"),
                    ("eds", "EDS (ЭЦП)"),
                    ("confirm", "Подтверждение в системе"),
                ],
                default="otp",
                max_length=10,
            ),
        ),
    ]
